version: "3"

services:
  transform-core-aio:
    profiles: ["with-transform-core-aio"]
    image: alfresco/alfresco-transform-core-aio:${TRANSFORMERS_TAG}
    environment:
      JAVA_OPTS: " -Xms256m -Xmx256m"
    ports:
      - "8090:8090"
  postgres:
    image: postgres:16.6
    profiles: ["default", "with-transform-core-aio", "postgres", "with-mtls-transform-core-aio", "with-sso"]
    environment:
      POSTGRES_PASSWORD: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_DB: alfresco
    command: postgres -c max_connections=300
    ports:
      - "5433:5432"
  activemq:
    profiles: ["default", "with-transform-core-aio", "activemq", "activemq6, ""with-mtls-transform-core-aio", "with-sso"]
    image: alfresco/alfresco-activemq:6.2-jre17-rockylinux8
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
    ports:
      - "5672:5672" # AMQP
      - "61616:61616" # OpenWire
      -
  activemq5:
    profiles: ["activemq5"]
    image: alfresco/alfresco-activemq:5.19.0-jre17-rockylinux8
    ports:
      - "5672:5672" # AMQP
      - "61616:61616" # OpenWire
  mtls-transform-core-aio:
    profiles: ["with-mtls-transform-core-aio"]
    image: quay.io/alfresco/alfresco-transform-core-aio:${TRANSFORMERS_TAG}
    hostname: transform-core-aio
    ports:
      - 8090:8090
    volumes:
      - ${CI_WORKSPACE}/keystores/tengineAIO/tengineAIO.truststore:/tengineAIO.truststore
      - ${CI_WORKSPACE}/keystores/tengineAIO/tengineAIO.keystore:/tengineAIO.keystore
    environment:
      ACTIVEMQ_URL: "nio://activemq:61616"
      ACTIVEMQ_USER: "admin"
      ACTIVEMQ_PASSWORD: "admin"
      LOG_LEVEL: debug

      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY_PASSWORD: "password"
      SERVER_SSL_KEY_STORE: "file:/tengineAIO.keystore"
      SERVER_SSL_KEY_STORE_PASSWORD: "password"
      SERVER_SSL_KEY_STORE_TYPE: "JCEKS"

      SERVER_SSL_CLIENT_AUTH: "need"
      SERVER_SSL_TRUST_STORE: "file:/tengineAIO.truststore"
      SERVER_SSL_TRUST_STORE_PASSWORD: "password"
      SERVER_SSL_TRUST_STORE_TYPE: "JCEKS"

      CLIENT_SSL_KEY_STORE: "file:/tengineAIO.keystore"
      CLIENT_SSL_KEY_STORE_PASSWORD: "password"
      CLIENT_SSL_KEY_STORE_TYPE: "JCEKS"

      CLIENT_SSL_TRUST_STORE: "file:/tengineAIO.truststore"
      CLIENT_SSL_TRUST_STORE_PASSWORD: "password"
      CLIENT_SSL_TRUST_STORE_TYPE: "JCEKS"
  keycloak:
    profiles: ["with-sso"]
    image: quay.io/keycloak/keycloak:26.5.0
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_DB: dev-file
    command: ["start-dev", "--import-realm", "--http-relative-path=/auth", "--hostname=localhost", "--http-enabled=true"]
    volumes:
      - ../../../repository/src/test/resources/realms/alfresco-realm.json:/opt/keycloak/data/import/alfresco-realm.json
    ports:
      - 8999:8080
