{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
{{- if and .Values.persistence.efs.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: content-services-pv
spec:
  capacity:
    storage: {{ .Values.persistence.baseSize | quote }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: {{ .Values.persistence.reclaimPolicy | default "Delete" }}
  nfs:
    server: "{{ .Values.persistence.efs.dns }}"
    path: "{{ .Values.persistence.efs.path }}"
  storageClassName: efs
---
{{- end -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: content-services-pvc
spec:
  accessModes: 
  {{ if .Values.persistence.efs.enabled }}
    - ReadWriteMany
  storageClassName: efs
  {{ else }}
    - ReadWriteOnce
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.database.persistence.size | quote }}
{{- end }}