version: "3"

services:
  alfresco:
     build:
        context: ./alfresco
     environment:
        - db.driver=org.postgresql.Driver
        - db.username=alfresco
        - db.password=alfresco
        - db.url=jdbc:postgresql://postgres:5432/alfresco
        - solr.host=solr6
        - solr.port=8983
        - solr.secureComms=none
        - solr.base.url=/solr
        - index.subsystem.name=solr6
     ports:
        - 8080:8080 #Browser port

  postgres:
     image: docker.io/library/postgres:9.4.12
     environment:
        - POSTGRES_PASSWORD=alfresco
        - POSTGRES_USER=alfresco
        - POSTGRES_DB=alfresco
     ports:
        - 5432:5432

  solr6:
     image: docker-internal.alfresco.com/search-services:1.1.0
     environment:
        #Solr needs to know how to register itself with Alfresco
        - SOLR_ALFRESCO_HOST=alfresco
        - SOLR_ALFRESCO_PORT=8080
        #Alfresco needs to know how to call solr
        - SOLR_SOLR_HOST=solr6
        - SOLR_SOLR_PORT=8983
        #Create the default alfresco and archive cores
        - SOLR_CREATE_ALFRESCO_DEFAULTS=alfresco,archive
     ports:
        - 8083:8983 #Browser port